### ISSUE TITLE
Not working in Turbolinks

### ISSUE THREAD

**Issue by lentg** [knapo/jquery-colorbox-rails#1]
Not working in Turbolinks

**Comment by sheldond** [comment]
It seems this issue still persists today, but a work-around is to call `$.colorbox.remove();` before calling colorbox, e.g.:

```
$.colorbox.remove();
$('.example').colorbox();
```

https://github.com/jackmoore/colorbox/issues/480

**Comment by gumlym** [comment]
Thanks @sheldond! That workaround is great
